### ISSUE TITLE
fusepy speed

### ISSUE THREAD

**Issue by ijiraq** [fusepy/fusepy#7]
Hi,  I wonder if the fuse.py speed is compromised someplace?  

I have fusepy-2.0.1 and OSXFUSE version 2.5.1 

I"ve made two mounts, one using the fuse.py loopback example and one using the 'c' Loopback that comes with OSXFUSE.    Reading through a 1.1GByte file I get the following times (in seconds):

filesystem 4.681068
c-Loopback 5.231013
py-Loopback 141.796592

so, I didn't think Python would be as quick as c but nearly 30 times slower is a major surprise. 

any ideas what might be going on here? 

JJ (aka ijiraq)

**Comment by arekbulski** [comment]
This article says that FUSE speed problems were fixed in the kernel, at some version.
https://www.phoronix.com/scan.php?page=article&item=zfs_fuse_performance&num=1

**Comment by eestrada** [comment]
With the advances in the the mainline FUSE, this may no longer be an issue. @ijiraq, is this still a problem for you?

**Comment by diman82** [comment]
@eestrada Seems it's still a problem.
I've run a SFTP example, and the read/write is extremely slow (~100-200kb/s)!
Is there a way to increase the chunk sizes? I can see on my SFTP server output, that each 'transfer' is 131,072 bytes (transferring 100mb file takes a hell lot of a time)..

**Comment by diman82** [comment]
@joe42 I set   
```
FUSE(MyOps, mountpoint, foreground=True, nothreads=True, big_writes=True, max_read=262144, max_write=262144)
```

But the read block size (buffer) is still set to: 131072

What I'm doing wrong? Is it possible to increase this value (I'm experimenting, as my read speeds are slow - ~1mb/s)?

**Comment by trapexit** [comment]
It's limited to 128KB in the kernel (though I believe the cap was to be raised in 4.20).

**Comment by diman82** [comment]
@trapexit 4.20?? The latest I see here is 3.4.1: https://github.com/libfuse/libfuse/releases

**Comment by paulo-raca** [comment]
He means Linux kernel 4.20 ;)
